"use client";

import React, { useState } from "react";
import jsPDF from "jspdf";
import ScoreRing from "./ScoreRing";
import BrandLogo from "./BrandLogo";
import { GeminiAnalysis } from "@/lib/services/gemini";

interface ResultDashboardProps {
  fileName: string;
  analysis: GeminiAnalysis;
  onReset: () => void;
}

export default function ResultDashboard({
  fileName,
  analysis,
  onReset,
}: ResultDashboardProps) {
  const [copied, setCopied] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  const handleCopySummary = () => {
    if (analysis.improved_summary) {
      navigator.clipboard.writeText(analysis.improved_summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadPdf = () => {
    try {
      setIsGeneratingPdf(true);
      const doc = new jsPDF();

      let yPos = 20;

      // Header Banner
      doc.setFillColor(0, 102, 204);
      doc.rect(0, 0, 210, 25, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.text("ResumeScanWala — AI ATS Analysis Report", 14, 16);

      yPos = 35;
      doc.setTextColor(29, 29, 31);
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.text(`File Analyzed: ${fileName}`, 14, yPos);
      doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, 14, yPos + 6);

      yPos += 18;
      // Scores
      doc.setDrawColor(220, 220, 220);
      doc.setFillColor(245, 245, 247);
      doc.roundedRect(14, yPos, 88, 25, 3, 3, "FD");
      doc.roundedRect(108, yPos, 88, 25, 3, 3, "FD");

      doc.setFontSize(10);
      doc.setTextColor(122, 122, 122);
      doc.text("ATS MATCH SCORE", 20, yPos + 8);
      doc.text("JOB MATCH PERCENTAGE", 114, yPos + 8);

      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 102, 204);
      doc.text(`${analysis.ats_score} / 100`, 20, yPos + 19);
      doc.text(`${analysis.jd_match_percentage}%`, 114, yPos + 19);

      yPos += 35;

      // Missing Keywords
      if (analysis.missing_keywords && analysis.missing_keywords.length > 0) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(29, 29, 31);
        doc.text("Missing Critical Keywords:", 14, yPos);
        yPos += 7;

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const keywordsText = analysis.missing_keywords.join(", ");
        const splitKeywords = doc.splitTextToSize(keywordsText, 180);
        doc.text(splitKeywords, 14, yPos);
        yPos += splitKeywords.length * 6 + 6;
      }

      // Improved Summary
      if (analysis.improved_summary) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(29, 29, 31);
        doc.text("AI-Recommended Resume Summary:", 14, yPos);
        yPos += 7;

        doc.setFontSize(9);
        doc.setFont("helvetica", "italic");
        doc.setTextColor(60, 60, 60);
        const splitSummary = doc.splitTextToSize(analysis.improved_summary, 180);
        doc.text(splitSummary, 14, yPos);
        yPos += splitSummary.length * 5 + 10;
      }

      // Section Analysis
      if (analysis.section_analysis && analysis.section_analysis.length > 0) {
        if (yPos > 230) {
          doc.addPage();
          yPos = 20;
        }

        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(29, 29, 31);
        doc.text("Section Breakdown & Feedback:", 14, yPos);
        yPos += 8;

        analysis.section_analysis.forEach((sec) => {
          if (yPos > 260) {
            doc.addPage();
            yPos = 20;
          }

          doc.setFontSize(10);
          doc.setFont("helvetica", "bold");
          doc.setTextColor(0, 102, 204);
          doc.text(`${sec.section} (${sec.score}/100)`, 14, yPos);
          yPos += 5;

          doc.setFontSize(9);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(50, 50, 50);
          const splitFeedback = doc.splitTextToSize(sec.feedback, 180);
          doc.text(splitFeedback, 14, yPos);
          yPos += splitFeedback.length * 5 + 4;
        });
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("Report generated by ResumeScanWala — https://resumescanwala.com", 14, 285);

      doc.save(`${fileName.replace(/\.[^/.]+$/, "")}_ATS_Report.pdf`);
    } catch (err) {
      console.error("PDF generation failed:", err);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  return (
    <section className="w-full bg-[#f5f5f7] py-12 px-4 sm:px-6">
      <div className="mx-auto max-w-5xl space-y-10">
        
        {/* Top Header Card */}
        <div className="glass-card p-6 sm:p-8 flex flex-col md:flex-row items-center justify-between gap-6 border-b border-[#e0e0e0]">
          <div className="flex items-center gap-4">
            <BrandLogo size="lg" />
            <div>
              <h2 className="text-xl sm:text-2xl font-bold text-[#1d1d1f]">
                Resume Analysis Completed
              </h2>
              <p className="text-xs sm:text-sm text-[#7a7a7a]">
                Analyzed file: <span className="font-semibold text-[#1d1d1f]">{fileName}</span>
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleDownloadPdf}
              disabled={isGeneratingPdf}
              className="btn-apple-primary text-sm py-2.5 px-5 shadow-sm disabled:opacity-50"
            >
              {isGeneratingPdf ? (
                "Generating PDF..."
              ) : (
                <span className="flex items-center gap-2">
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  Download PDF Report
                </span>
              )}
            </button>

            <button
              onClick={onReset}
              className="btn-apple-secondary text-sm py-2.5 px-4"
            >
              Scan Another
            </button>
          </div>
        </div>

        {/* Score Benchmark Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="glass-card p-8 flex flex-col items-center justify-center text-center">
            <ScoreRing
              score={analysis.ats_score}
              label="ATS Benchmark Score"
              subtitle={
                analysis.ats_score >= 80
                  ? "Top Candidate Match"
                  : analysis.ats_score >= 60
                  ? "Moderate ATS Pass"
                  : "Needs Keywords Optimization"
              }
            />
          </div>

          <div className="glass-card p-8 flex flex-col items-center justify-center text-center">
            <ScoreRing
              score={analysis.jd_match_percentage}
              label="Job Description Match"
              subtitle={
                analysis.jd_match_percentage >= 75
                  ? "High Role Alignment"
                  : "Partial Requirement Match"
              }
            />
          </div>
        </div>

        {/* Missing Keywords & Skills Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Missing Keywords */}
          <div className="glass-card p-6 sm:p-8">
            <div className="flex items-center gap-2 mb-4">
              <div className="p-2 rounded-lg bg-amber-100 text-amber-700">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
              </div>
              <h3 className="text-lg font-bold text-[#1d1d1f]">
                Missing ATS Keywords
              </h3>
            </div>
            <p className="text-xs text-[#7a7a7a] mb-4">
              Recruiter filters often look for these exact terms in your resume:
            </p>

            {analysis.missing_keywords?.length > 0 ? (
              <div className="flex flex-wrap gap-2">
                {analysis.missing_keywords.map((kw, idx) => (
                  <span
                    key={idx}
                    className="text-xs bg-red-50 text-red-700 font-medium px-3 py-1.5 rounded-full border border-red-200"
                  >
                    + {kw}
                  </span>
                ))}
              </div>
            ) : (
              <p className="text-xs text-emerald-600 font-medium">
                Great job! No major missing keywords detected.
              </p>
            )}
          </div>

          {/* Top Matching vs Missing Skills */}
          <div className="glass-card p-6 sm:p-8">
            <div className="flex items-center gap-2 mb-4">
              <div className="p-2 rounded-lg bg-emerald-100 text-emerald-700">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <h3 className="text-lg font-bold text-[#1d1d1f]">
                Matched Skills Overview
              </h3>
            </div>

            <div className="space-y-4">
              <div>
                <span className="text-xs uppercase font-semibold text-emerald-700 block mb-1.5">
                  Top Matched Skills
                </span>
                <div className="flex flex-wrap gap-1.5">
                  {analysis.top_matching_skills?.map((sk, idx) => (
                    <span
                      key={idx}
                      className="text-xs bg-emerald-50 text-emerald-700 px-2.5 py-1 rounded-md border border-emerald-200"
                    >
                      ✓ {sk}
                    </span>
                  )) || <span className="text-xs text-gray-400">None detected</span>}
                </div>
              </div>

              <div>
                <span className="text-xs uppercase font-semibold text-amber-700 block mb-1.5">
                  Skills to Add
                </span>
                <div className="flex flex-wrap gap-1.5">
                  {analysis.missing_skills?.map((sk, idx) => (
                    <span
                      key={idx}
                      className="text-xs bg-amber-50 text-amber-700 px-2.5 py-1 rounded-md border border-amber-200"
                    >
                      ! {sk}
                    </span>
                  )) || <span className="text-xs text-gray-400">None</span>}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* AI Rewritten Summary */}
        {analysis.improved_summary && (
          <div className="glass-card p-6 sm:p-8 bg-gradient-to-br from-white via-white to-[#0066cc]/5 border border-[#0066cc]/20">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <BrandLogo size="sm" showText={false} />
                <h3 className="text-lg font-bold text-[#1d1d1f]">
                  AI Recommended Resume Summary
                </h3>
              </div>
              <button
                onClick={handleCopySummary}
                className="text-xs bg-[#0066cc] text-white hover:bg-[#0052a3] px-3 py-1.5 rounded-full transition-all"
              >
                {copied ? "Copied to Clipboard!" : "Copy Summary"}
              </button>
            </div>
            <p className="text-sm text-[#1d1d1f] leading-relaxed italic bg-white p-4 rounded-xl border border-gray-200">
              "{analysis.improved_summary}"
            </p>
          </div>
        )}

        {/* Section-by-Section Breakdown */}
        {analysis.section_analysis && analysis.section_analysis.length > 0 && (
          <div className="glass-card p-6 sm:p-8">
            <h3 className="text-xl font-bold text-[#1d1d1f] mb-6">
              Section Breakdown & Action Plan
            </h3>

            <div className="space-y-6">
              {analysis.section_analysis.map((sec, idx) => (
                <div
                  key={idx}
                  className="p-5 rounded-2xl bg-white border border-[#e0e0e0] space-y-3"
                >
                  <div className="flex items-center justify-between">
                    <h4 className="text-base font-semibold text-[#1d1d1f]">
                      {sec.section}
                    </h4>
                    <span
                      className={`text-xs font-bold px-3 py-1 rounded-full ${
                        sec.score >= 80
                          ? "bg-emerald-100 text-emerald-800"
                          : sec.score >= 60
                          ? "bg-amber-100 text-amber-800"
                          : "bg-red-100 text-red-800"
                      }`}
                    >
                      {sec.score} / 100
                    </span>
                  </div>

                  <p className="text-xs sm:text-sm text-[#333333] leading-normal">
                    {sec.feedback}
                  </p>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2 text-xs">
                    {sec.strengths?.length > 0 && (
                      <div className="bg-emerald-50/60 p-3 rounded-xl border border-emerald-100">
                        <strong className="text-emerald-800 block mb-1">Strengths:</strong>
                        <ul className="list-disc list-inside text-emerald-900 space-y-1">
                          {sec.strengths.map((str, sIdx) => (
                            <li key={sIdx}>{str}</li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {sec.improvements?.length > 0 && (
                      <div className="bg-amber-50/60 p-3 rounded-xl border border-amber-100">
                        <strong className="text-amber-800 block mb-1">Improvements Needed:</strong>
                        <ul className="list-disc list-inside text-amber-900 space-y-1">
                          {sec.improvements.map((imp, iIdx) => (
                            <li key={iIdx}>{imp}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* General Issues & Recommendations */}
        {analysis.suggestions && analysis.suggestions.length > 0 && (
          <div className="glass-card p-6 sm:p-8">
            <h3 className="text-lg font-bold text-[#1d1d1f] mb-4">
              General Recommendations for Recruiters
            </h3>
            <ul className="space-y-2 text-xs sm:text-sm text-[#333333]">
              {analysis.suggestions.map((sug, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-[#0066cc] font-bold">•</span>
                  <span>{sug}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

      </div>
    </section>
  );
}
